    SELECT 
        DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
    FROM 
        ONLINE_SALE
    WHERE 
        YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
UNION
    SELECT
        SALES_DATE,
        PRODUCT_ID,
        NULL AS USER_ID,
        SALES_AMOUNT
    FROM
        OFFLINE_SALE
    WHERE 
        YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
ORDER BY
    1 ASC, 2 ASC, 3 ASC;