WITH CARE_DURATION 
AS (
    SELECT 
        I.ANIMAL_ID, I.NAME, DATEDIFF(O.DATETIME, I.DATETIME) AS DURATION
    FROM
        ANIMAL_INS I
    JOIN
        ANIMAL_OUTS O
    ON
        I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY
        3 DESC
    LIMIT 2
)

SELECT
    ANIMAL_ID, NAME
FROM
    CARE_DURATION
    
    