-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'I%'
    AND (SEX_UPON_OUTCOME LIKE 'S%' 
         OR SEX_UPON_OUTCOME LIKE 'N%')
ORDER BY 1;