SELECT YEAR(S.SALES_DATE) AS YEAR,
       MONTH(S.SALES_DATE) AS MONTH,
       GENDER AS GENDER,
       COUNT(DISTINCT(I.USER_ID)) AS USERS
FROM (SELECT *
      FROM USER_INFO
      WHERE GENDER IS NOT NULL) I
    JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;