SELECT YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT(I.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(I.USER_ID)) / (SELECT COUNT(*) 
                                 FROM USER_INFO 
                                 WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM USER_INFO I
    JOIN ONLINE_SALE O 
    ON I.USER_ID = O.USER_ID
WHERE YEAR(I.JOINED) = 2021
GROUP BY 1, 2
ORDER BY 1, 2;