-- 코드를 입력하세요
SELECT writer_id, nickname, sum(price) as TOTAL_SALES
FROM USED_GOODS_BOARD UGB
    Left OUTER JOIN USED_GOODS_USER UGU 
    ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
group by writer_id
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;