SELECT MONTH(START_DATE) AS MONTH, 
       CAR_ID AS CAR_ID, 
       COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE YEAR(START_DATE) = 2022
                AND MONTH(START_DATE) IN (8, 9, 10)
                GROUP BY CAR_ID
                HAVING COUNT(*) >= 5)
    AND YEAR(START_DATE) = 2022
    AND MONTH(START_DATE) IN (8, 9, 10)
GROUP BY 1, 2
ORDER BY 1, 2 DESC;

