-- 코드를 작성해주세요
WITH CATCH_COUNT AS (
    SELECT 
        N.FISH_NAME AS NAME,
        COUNT(*) AS FISH_COUNT
    FROM
        FISH_INFO F
    JOIN
        FISH_NAME_INFO N
    WHERE 
        F.FISH_TYPE = N.FISH_TYPE
    GROUP BY
        N.FISH_NAME
)

SELECT 
    SUM(FISH_COUNT) AS FISH_COUNT
FROM
    CATCH_COUNT
WHERE
    NAME IN ("BASS", "SNAPPER");
    