WITH OCTOBER_RENTAL_HISTORY 
AS (
    SELECT 
        *
    FROM    
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        MONTH(START_DATE) = 10
)

SELECT 
    DISTINCT(C.CAR_ID)
FROM 
    CAR_RENTAL_COMPANY_CAR C
JOIN
    OCTOBER_RENTAL_HISTORY H
ON
    C.CAR_ID = H.CAR_ID
WHERE
    CAR_TYPE = '세단'
ORDER BY
    1 DESC;