WITH MOST_VIEWED_BOARD 
AS (
    SELECT 
        *
    FROM
        USED_GOODS_BOARD
    ORDER BY 
        VIEWS DESC
    LIMIT 1
)

SELECT 
    CONCAT('/home/grep/src/', 
           B.BOARD_ID, '/', 
           FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM
    MOST_VIEWED_BOARD B
JOIN 
    USED_GOODS_FILE F
ON B.BOARD_ID = F.BOARD_ID
ORDER BY 
    FILE_ID DESC;
    

    
