SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B
    JOIN (SELECT *
          FROM BOOK_SALES 
          WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
          ) S
    ON B.BOOK_ID = S.BOOK_ID
GROUP BY 1
ORDER BY 1;
