WITH MOST_EXPENSIVE_PRODUCT AS (
    SELECT 
        CATEGORY, MAX(PRICE) AS PRICE
    FROM 
        FOOD_PRODUCT
    GROUP BY
        1
)

SELECT
    F.CATEGORY, F.PRICE AS MAX_PRICE, PRODUCT_NAME
FROM 
    FOOD_PRODUCT F
JOIN 
    MOST_EXPENSIVE_PRODUCT E
ON 
    F.CATEGORY = E.CATEGORY AND F.PRICE = E.PRICE
HAVING 
    F.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY
    2 DESC;
    