WITH BEST_FOOD_PRODUCT AS (
    SELECT 
        (ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC)) AS NUM,
        CATEGORY,
        PRICE,
        PRODUCT_NAME
    FROM
        FOOD_PRODUCT
)

SELECT
    CATEGORY,
    PRICE,
    PRODUCT_NAME
FROM
    BEST_FOOD_PRODUCT
WHERE
    CATEGORY IN ("과자", "국", "김치", "식용유") AND NUM = 1
ORDER BY
    2 DESC;